### ISSUE TITLE
Debugging/Build Error

### ISSUE THREAD

**Issue by AxtonGTV** [AlexanderLindsay/PredictionMarketBot#2]
So whenever I try to run the program, an error message pops up, two errors actually. And it won't let me run it. There is something wrong with the debug folder (or so it says). Can you help me figure this out?
![capture](https://user-images.githubusercontent.com/45834905/49905343-4e00c900-fe3b-11e8-9d96-af7800688e32.PNG)
![2](https://user-images.githubusercontent.com/45834905/49905341-4b9e6f00-fe3b-11e8-85f4-bb138e32b1ae.PNG)

Thanks!

**Comment by AlexanderLindsay** [comment]
So I notice that you don't have a `secrets.config` file in the solution explorer window. That file is needed to get this to work both because it is referenced when running it and because there is a build step that puts it into the output directory.

You can check the readme for details on the `secrets.config` file, but basic template is the following:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<appSettings>
  <add key="token" value="YourTokenHere"/>
</appSettings>
```

I am debugging blind here so I am not sure that is the problem so let me know if that works or not. If I am correct and it is the missing file that is the problem you should see the following error message in the build errors (I shorted the path to the relevant file but it shows the full path):
```
Could not copy the file "secrets.config" because it was not found.			
```

**Comment by AxtonGTV** [comment]
Thank you
